[profile.default]
src = "src"
out = "out"
libs = ["lib"]


[profile.rpc]
# unichain = "https://unichain-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
